### ISSUE TITLE
Fails on original doom mus file

### ISSUE THREAD

**Issue by AmanitaVerna** [doomjs/opl3#1]
Installed with npm as per instructions. Ran from npm command prompt.

using opl3 --wav --mus 03.mus

(03.mus is just "03 - At Doom's Gate.mus" renamed - I acquired it from http://www.vgmpf.com/Wiki/index.php?title=Doom_(DOS) for testing after opl3 failed in the same way on a mus file that I created myself)

```
Your environment has been set up for using Node.js 4.4.4 (x64) and npm.

...

OPL3 emulator v0.1.5
C:\Users\Richard\AppData\Roaming\npm\node_modules\opl3\format\mus.js:126
                            this.channels[channel].instrument = this.instruments
[value];

^

TypeError: Cannot read property '30' of undefined
    at MUS.extend.update (C:\Users\Richard\AppData\Roaming\npm\node_modules\opl3
\format\mus.js:126:81)
    at Object.<anonymous> (C:\Users\Richard\AppData\Roaming\npm\node_modules\opl
3\cli.js:114:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by doomjs** [comment]
Hi @Trafalg,
fixed the issue by including a default GENMIDI lump. This was generated by a coming Doom toolset. Stay tuned, I will release the toolset in a month focusing on exporting features (all resources from a WAD file).
